### ISSUE TITLE
unable to start a lab

### ISSUE THREAD

**Issue by arturrudzinski** [spurin/diveintoansible-lab-gcp-cloudshell#1]
Hello, I tried multiple times, on different google accounts and the LAB if i click the button does not start 

Message is 
**Cloud Shell is experiencing some issues provisioning a VM to you. Please try again in a few minutes.**

**Comment by spurin** [comment]
Thanks @arturrudzinski 

What region are you connecting from please?

**Comment by spurin** [comment]
Raised  -  https://stackoverflow.com/questions/69348852/customised-google-cloudshell-image-does-not-launch

**Comment by spurin** [comment]
Hi @arturrudzinski 

Thanks for your patience on this.  A friend of mine at Google was able to shed some light on this with some internal questions.  

Looks like the image that it was built from needs to be updated regularly for Google to support it.  I had it working and it worked for a few days but then, stopped working.

I've now updated the image.

Would you give it another try please and let me know if it's resolved?

Many Thanks


James Spurin

**Comment by arturrudzinski** [comment]
Hello, i tried to open and it seems it works ! THX ! if any other issues i will let you know.

**Comment by spurin** [comment]
Awesome! Thanks @arturrudzinski
